import Head from 'next/head'
import Image from 'next/image'
import Card from '../components/card'
import Heading from '../components/heading'
import Hero from '../components/hero'
import NavBar from '../components/navbar'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar logo="Loans" />
      <main className={styles.main}>
        <Hero
          source="/hands.png"
          main_text="Earn 6% interest on your FD &amp;"
          sub_text="Get a lifetime free Step Up Credit Card"
        />
        <Heading text="Cards &amp; loans" />
        <div className={styles.card_section}>
          <Card
            heading="Credit Cards"
            text="Choose a card matching your lifestyle needs"
            url="/"
            link_text="Get a Card"
          />
          <Card
            heading="Personal Loans"
            text="Select the best offer curated just for you"
            url="/"
            link_text="Check Eligibility"
          />
          <Card
            heading="Micro Loans"
            text="Instant small ticket loands to meet your cash needs"
            url="/"
            link_text="Get Instant Loan"
          />
          <Card
            heading="Business Loan"
            text="Expand your business with loans at a low rate"
            url="/"
            link_text="Check Eligibility"
          />
        </div>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
